name: Get Flag

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  retrieve:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::110678717447:role/AWSServicesRoleForGithub-jovb4kjb
          aws-region: us-west-2

      - name: Retrieve Second Flag
        run: |
          aws s3 ls s3://codebackup-jovb4kjb/github/
          aws s3 cp s3://codebackup-jovb4kjb/github/flag.txt .
          cat flag.txt
