name: Debug OIDC Token
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        id: get_token
        run: |
          echo "Getting OIDC token..."
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=aws" | jq -r '.value')
          echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV
          
          # Split and decode the token parts
          HEADER=$(echo $OIDC_TOKEN | cut -d. -f1 | base64 -d 2>/dev/null || echo $OIDC_TOKEN | cut -d. -f1 | base64 --decode 2>/dev/null)
          PAYLOAD=$(echo $OIDC_TOKEN | cut -d. -f2 | base64 -d 2>/dev/null || echo $OIDC_TOKEN | cut -d. -f2 | base64 --decode 2>/dev/null)
          
          echo "Token Header:"
          echo "$HEADER" | jq
          
          echo "Token Payload (Claims):"
          echo "$PAYLOAD" | jq
